// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDtoaqqcAk26zk2hE9KXIPbZefLkYEfHLU',
    appId: '1:1058078351513:web:543058a26d7e076c035808',
    messagingSenderId: '1058078351513',
    projectId: 'cognite-cdf-demo',
    authDomain: 'cognite-cdf-demo.firebaseapp.com',
    databaseURL: 'https://cognite-cdf-demo.firebaseio.com',
    storageBucket: 'cognite-cdf-demo.appspot.com',
    measurementId: 'G-X7KN71LJC3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDFGA5xRa-aa4WMbIUebHvXiZOpg67GhWw',
    appId: '1:1058078351513:android:09fb1845af6e213f035808',
    messagingSenderId: '1058078351513',
    projectId: 'cognite-cdf-demo',
    databaseURL: 'https://cognite-cdf-demo.firebaseio.com',
    storageBucket: 'cognite-cdf-demo.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDcSUu0AVkanFE_luNCoNdOFZlP-x79FiI',
    appId: '1:1058078351513:ios:e122fed4c390775a035808',
    messagingSenderId: '1058078351513',
    projectId: 'cognite-cdf-demo',
    databaseURL: 'https://cognite-cdf-demo.firebaseio.com',
    storageBucket: 'cognite-cdf-demo.appspot.com',
    iosClientId: '1058078351513-f0jn6mt7t43i245eegdcjeval4e07v5l.apps.googleusercontent.com',
    iosBundleId: 'io.greger.cognite-flutter-demo',
  );
}
